namespace LmKitOmniApi.Infrastructure.AI.ComputerUse;

/// <summary>
/// One request to gate a side-effecting computer-use action on human approval.
/// <see cref="ApprovalId"/> is generated by the loop and echoed to the client in the
/// <c>[HITL_APPROVAL_REQUIRED:{id}]</c> marker BEFORE the gate is awaited, so the id the
/// human resolves is the same one the loop is waiting on. <see cref="SessionId"/> is the
/// hidden computer-use session that scopes the approval record.
/// </summary>
public sealed record ComputerUseApprovalRequest(
    Guid ApprovalId,
    Guid TenantId,
    Guid UserId,
    Guid SessionId,
    string ActionSummary,
    string Details);

/// <summary>
/// Gates a side-effecting computer-use action (navigate / click / type / key) on a human
/// decision. Kept as a seam so the loop is unit-testable with a scripted approver: the
/// tests inject a fake that returns true/false without any database or UI.
///
/// The default implementation (<see cref="ComputerUseApprovalGate"/>) reuses the existing
/// approval substrate — it creates a <c>TaskApproval</c> row (owner-scoped, encrypted
/// payload) that surfaces in the user's pending-approvals list, then waits for a human
/// decision. Read-only actions never reach this gate; the loop calls it only for
/// side-effecting actions when <see cref="ComputerUseOptions.RequireApprovalPerAction"/>
/// is set. It fails CLOSED: any error, timeout, or ambiguous state yields false.
/// </summary>
public interface IComputerUseApprovalGate
{
    /// <summary>Returns true only if a human explicitly approved the action; false otherwise (fail-closed).</summary>
    Task<bool> RequestAsync(ComputerUseApprovalRequest request, CancellationToken ct = default);
}
